# Generated by Django 5.0.7 on 2025-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, max_length=200, null=True)),
                ('asking', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
