# Generated by Django 5.2.6 on 2026-02-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='purpose_teams',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
