# Generated by Django 5.0.7 on 2025-11-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
