# Generated by Django 5.2.6 on 2026-02-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_day_purpose_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
