# Generated by Django 5.2.6 on 2026-02-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_milestone_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hard_deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
