# Generated by Django 5.2.6 on 2026-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_task_hard_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dependency',
            name='weight',
            field=models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak'), ('suggestion', 'Suggestion')], default='strong', max_length=20),
        ),
    ]
