# Generated by Django 5.0.7 on 2025-12-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('nachtakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vortakte', to='api.task')),
                ('vortakt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachtakte', to='api.task')),
            ],
            options={
                'unique_together': {('vortakt', 'nachtakt')},
            },
        ),
    ]
