# Generated by Django 5.2.6 on 2026-02-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_dependency_weight_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_index', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=1)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('order_index', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.project')),
            ],
            options={
                'ordering': ['project', 'order_index', 'start_index'],
            },
        ),
    ]
