# Generated by Django 5.2.6 on 2026-02-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_dependency_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencyview',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
