# Generated by Django 5.0.7 on 2025-12-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_dependency_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together=set(),
        ),
    ]
