# Generated by Django 5.0.7 on 2025-12-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dependency_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('vortakt', 'nachtakt')},
        ),
    ]
