# Generated by Django 5.2.6 on 2026-02-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_usershortcuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Persona', max_length=200)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('hair_color', models.CharField(default='#4a3728', max_length=20)),
                ('day_index', models.IntegerField(default=0)),
                ('order_index', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protopersonas', to='api.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protopersonas', to='api.task')),
            ],
            options={
                'ordering': ['project', 'order_index'],
            },
        ),
    ]
