# Generated by Django 5.0.7 on 2025-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='attempt',
            unique_together={('task', 'number')},
        ),
    ]
