# Generated by Django 5.2.6 on 2026-02-19 22:43
# Creates ProtoPersona with milestone FK — 0014 transitions to M2M.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_usershortcuts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtoPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#f87171', max_length=20)),
                ('x', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protopersonas', to='api.milestone')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_protopersonas', to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protopersonas', to='api.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
