# Generated by Django 5.0.7 on 2026-02-21 12:45
# Manually edited to use RenameModel/RenameField to preserve existing data.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_unified_idea_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename LegendVariant → Dimension (preserves all rows)
        migrations.RenameModel(
            old_name='LegendVariant',
            new_name='Dimension',
        ),
        # Rename the FK field on LegendType: variant → dimension
        migrations.RenameField(
            model_name='legendtype',
            old_name='variant',
            new_name='dimension',
        ),
        # Update Dimension's related_name on Project FK
        migrations.AlterField(
            model_name='dimension',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='dimensions',
                to='api.project',
            ),
        ),
        # Update created_by related_name on Dimension
        migrations.AlterField(
            model_name='dimension',
            name='created_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_dimensions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add IdeaReference model
        migrations.CreateModel(
            name='IdeaReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('headline', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_idea_references', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_references', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        # Add idea_reference FK to Idea
        migrations.AddField(
            model_name='idea',
            name='idea_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.ideareference'),
        ),
    ]
