# Generated by Django 5.2.6 on 2026-02-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_category_owner_idea_owner_dimension_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='order_index',
        ),
        migrations.AddField(
            model_name='idea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='IdeaPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='api.idea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_placements', to='api.project')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
    ]
