# Generated by Django 5.2.6 on 2026-02-21 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_idea_placement_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='legend_type',
        ),
        migrations.CreateModel(
            name='IdeaDimensionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_type_assignments', to='api.dimension')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_types', to='api.idea')),
                ('legend_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_assignments', to='api.legendtype')),
            ],
            options={
                'unique_together': {('idea', 'dimension')},
            },
        ),
    ]
