# Generated by Django 5.2.6 on 2026-02-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_idea_dimension_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ideaplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('idea', 'category'), name='unique_idea_per_category'),
        ),
    ]
