# Generated by Django 5.2.6 on 2026-02-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_scoped_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
