# Generated by Django 5.2.6 on 2026-02-21 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_dimension_to_legend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealegendtype',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend_types', to='api.idea'),
        ),
        migrations.AlterField(
            model_name='legend',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlegendadoption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_legends', to=settings.AUTH_USER_MODEL),
        ),
    ]
