# Generated by Django 5.2.6 on 2025-12-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AttemptTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='api.attempt')),
            ],
        ),
    ]
