# Generated by Django 5.2.6 on 2025-12-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_attempt_done_alter_attempt_number_attempttodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
