# Generated by Django 5.2.6 on 2026-02-21 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_context_categorycontextplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegendContextPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend_placements', to='api.context')),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_placements', to='api.legend')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('legend', 'context')},
            },
        ),
    ]
