# Generated by Django 5.2.6 on 2026-02-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_legend_context_placement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserContextAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopters', to='api.context')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'context')},
            },
        ),
    ]
