# Generated by Django 5.2.6 on 2026-02-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
