# Generated by Django 5.2.6 on 2026-02-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_context_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='filter_state',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
