# Generated by Django 5.2.6 on 2026-01-19 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Demo Date',
            },
        ),
    ]
