# Generated by Django 5.2.6 on 2026-01-19 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_demodate'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.attempt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('team_joined', 'Team Joined'), ('team_left', 'Team Left'), ('attempt_upcoming', 'Attempt Upcoming'), ('attempt_today', 'Attempt Today'), ('attempt_overdue', 'Attempt Overdue'), ('general', 'General Notification')], default='general', max_length=50),
        ),
    ]
