# Generated by Django 5.2.6 on 2026-02-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_context_filter_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='legendtype',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
