# Generated by Django 5.2.6 on 2026-02-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_legendtype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
