# Generated by Django 5.2.6 on 2026-02-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_category_filter_config'),
        ('api', '0031_formation_is_default'),
    ]

    operations = [
    ]
