# Generated by Django 5.2.6 on 2026-02-15 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_category_legendtype_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.project'),
        ),
        migrations.AddField(
            model_name='idea',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='api.project'),
        ),
        migrations.AddField(
            model_name='legendtype',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legend_types', to='api.project'),
        ),
    ]
