# Generated by Django 5.2.6 on 2026-02-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_idea_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershortcuts',
            name='filter_presets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
