# Generated by Django 5.0.7 on 2026-02-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_category_project_idea_project_legendtype_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='nachtakt',
        ),
        migrations.RemoveField(
            model_name='dependency',
            name='vortakt',
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Dependency',
        ),
    ]
