# Generated by Django 5.2.6 on 2026-02-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_dependency_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['team', 'order_index']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['project', 'order_index']},
        ),
        migrations.AddField(
            model_name='task',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='team_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_index', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='api.milestone')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='api.milestone')),
            ],
        ),
    ]
