# Generated by Django 5.2.6 on 2026-02-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_usershortcuts_filter_presets'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='api.context'),
        ),
    ]
