# Generated by Django 5.2.6 on 2026-02-24 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_context_is_default_formation_context_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='api.context'),
        ),
    ]
