# Generated by Django 5.2.6 on 2026-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_task_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_attempt',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_unassigned', 'Task Unassigned'), ('team_joined', 'Team Joined'), ('team_left', 'Team Left'), ('general', 'General Notification')], default='general', max_length=50),
        ),
    ]
