# Generated by Django 5.2.6 on 2026-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_idea_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
