# Generated by Django 5.2.6 on 2026-02-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_idea_title_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaContextPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_placements', to='api.context')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_placements', to='api.idea')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('idea', 'context')},
            },
        ),
    ]
