# Generated by Django 5.2.6 on 2026-02-25 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_add_idea_context_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContextPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_placements', to='api.context')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_placements', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'context')},
            },
        ),
    ]
