# Generated by Django 5.2.6 on 2026-02-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_project_context_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershortcuts',
            name='default_context',
            field=models.ForeignKey(blank=True, help_text="The user's chosen default context (auto-loaded on open).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.context'),
        ),
    ]
