# Generated by Django 5.0.7 on 2026-02-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_usershortcuts_default_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='asking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
