# Generated by Django 5.0.7 on 2026-02-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_asking_to_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='asking',
        ),
        migrations.AddField(
            model_name='task',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AcceptanceCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_criteria', to='api.task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
