# Generated by Django 5.0.7 on 2026-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_task_structure_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
