# Generated by Django 5.0.7 on 2026-02-27 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_add_dependency_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_add_system_prompt', models.BooleanField(default=False)),
                ('auto_add_json_format', models.BooleanField(default=False)),
                ('auto_add_scenario_prompt', models.BooleanField(default=False)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('scenario_prompts', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prompt settings',
            },
        ),
    ]
