# Generated by Django 5.0.7 on 2026-02-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_prompt_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptsettings',
            name='auto_add_end_prompt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptsettings',
            name='auto_add_project_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptsettings',
            name='end_prompt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
