# Generated by Django 5.2.6 on 2026-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_workspace_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
