# Generated by Django 5.2.6 on 2026-03-06 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_milestone_todo_from_is_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonetodo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TaskLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='General', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_legends', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_legends', to='api.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskLegendType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='api.tasklegend')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TaskLegendAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='api.tasklegend')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legend_assignments', to='api.task')),
                ('legend_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='api.tasklegendtype')),
            ],
            options={
                'unique_together': {('task', 'legend')},
            },
        ),
    ]
