# Generated by Django 5.0.7 on 2026-03-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_milestone_todo_from_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonetodo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
