# Generated by Django 5.0.7 on 2026-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_default_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptsettings',
            name='auto_add_system_prompt',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promptsettings',
            name='system_prompt',
            field=models.TextField(blank=True, default="You are a project management AI assistant working inside Orgarhythmus, a structured planning tool. Your role is to help users organise their projects by generating or refining tasks, teams, milestones, ideas, categories, legends, and dependency schedules based on the provided project data.\n\nRules you must follow:\n- Respond with valid JSON only — no markdown fences, no prose, no explanations outside the JSON.\n- Match the requested JSON format exactly; do not add extra keys or change field names.\n- When working with milestones, the scheduling constraint is strict: a predecessor's last day (start_index + duration) must be ≤ its successor's start_index. Never propose changes that violate this rule; if unavoidable, note the conflict in a 'conflict_reason' field.\n- Keep all generated names and descriptions concise, specific, and actionable."),
        ),
    ]
