# Generated by Django 5.0.7 on 2026-03-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_task_legend_system'),
        ('api', '0054_alter_promptsettings_auto_add_system_prompt_and_more'),
    ]

    operations = [
    ]
