# Generated by Django 5.0.7 on 2026-03-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_main_branches(apps, schema_editor):
    """
    For every existing Project, create a main Branch and assign all branch-aware
    rows (Team, Task, Milestone, Phase, TaskLegend, Day) to it.
    """
    Project = apps.get_model("api", "Project")
    Branch = apps.get_model("api", "Branch")
    Team = apps.get_model("api", "Team")
    Task = apps.get_model("api", "Task")
    Milestone = apps.get_model("api", "Milestone")
    Phase = apps.get_model("api", "Phase")
    TaskLegend = apps.get_model("api", "TaskLegend")
    Day = apps.get_model("api", "Day")

    for project in Project.objects.all():
        branch = Branch.objects.create(
            project=project,
            name="main",
            is_main=True,
            description="Auto-created main branch during migration.",
        )
        Team.objects.filter(project=project).update(branch=branch)
        Task.objects.filter(project=project).update(branch=branch)
        Milestone.objects.filter(project=project).update(branch=branch)
        Phase.objects.filter(project=project).update(branch=branch)
        TaskLegend.objects.filter(project=project).update(branch=branch)
        Day.objects.filter(project=project).update(branch=branch)


def reverse_main_branches(apps, schema_editor):
    """Reverse: delete all Branch rows (FK fields already allow null)."""
    Branch = apps.get_model("api", "Branch")
    Branch.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_merge_20260320_1315'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptsettings',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are an expert project management AI embedded in Orgarhythmus — a structured planning tool for organising tasks, teams, milestones, dependencies, ideas, categories, and legends.\n\nYou receive a JSON payload with live project data and scenario-specific instructions. Your job is to generate or refine project content accordingly.\n\nOutput rules:\n- Respond with valid JSON only — no markdown fences, no prose, no explanations outside the JSON.\n- Match the expected JSON schema exactly; do not add, rename, or omit fields.\n- Ground suggestions in the provided data; avoid inventing names or structures that contradict existing context.\n- Keep all names and descriptions concise, specific, and actionable.'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_main', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_branches', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='api.project')),
                ('source_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_branches', to='api.branch')),
            ],
            options={
                'ordering': ['-is_main', 'created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='day',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.branch'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='api.branch'),
        ),
        migrations.AddField(
            model_name='phase',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.branch'),
        ),
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.branch'),
        ),
        migrations.AddField(
            model_name='tasklegend',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_legends', to='api.branch'),
        ),
        migrations.AddField(
            model_name='team',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.branch'),
        ),
        migrations.RunPython(create_main_branches, reverse_main_branches),
    ]
