# Generated by Django 5.0.7 on 2026-03-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_promptsettings_system_prompt_branch_day_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='demo_index',
            field=models.IntegerField(blank=True, help_text='Current timeline cursor position (only meaningful when is_demo=True).', null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='metric',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('months', 'Months')], default='days', help_text="Unit of time used by this project's timeline index.", max_length=20),
        ),
    ]
